### ISSUE TITLE
Insert all records in one go

### ISSUE THREAD

**Issue by fekete965** [0xSooki/nft-rarity-generator#10]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] This is a feature request only 💡
- [x] I checked to make sure that this feature has NOT already been requested

**Why are you requesting this feature**
At the moment when we save the data to the DB we do it one by one, which in my opinion is not very efficient.

**Describe the solution you'd like**
We should prepare all the records first, then use `.insertMany` to insert all the records into the DB in one go.

**Comment by fekete965** [comment]
I would love to solve this problem myself.

**Comment by 0xSooki** [comment]
Amazing, I love your enthusiasm :)

**Comment by fekete965** [comment]
@0xSooki sorry for the silly question, but how has the right to push to the `develop` branch?

**Comment by 0xSooki** [comment]
I will be merging the prs to the `develop` branch

**Comment by fekete965** [comment]
I understand that, but can anybody create PRs locally originated in that branch?

**Comment by 0xSooki** [comment]
I believe so, but wouldn't bet on it

**Comment by fekete965** [comment]
@0xSooki I believe that the forked repos will not see the `develop` branch. 😞

**Comment by 0xSooki** [comment]
When forking a repo it asks if you only want to work main branch can't that be the case?

**Comment by fekete965** [comment]
@0xSooki you are right! I had to add it manually. 😅

**Comment by 0xSooki** [comment]
Everything working perfectly?

**Comment by fekete965** [comment]
Yes. Everything is fine now. Refactor PR has been rebased on develop and conflicts were addressed.
I am working on inserting all records into the DB atm.

**Comment by 0xSooki** [comment]
Will test it soon on develop than merging it to main

**Comment by 0xSooki** [comment]
Started testing, however the trait values are nulls, any idea why?
![image](https://user-images.githubusercontent.com/65089621/193931960-84e7380c-2be8-4c86-83de-67de83b46227.png)

**Comment by fekete965** [comment]
@0xSooki I'll start investigating it.

**Comment by fekete965** [comment]
@0xSooki it seems like a valid value to me. 🤔

**Comment by fekete965** [comment]
@0xSooki we add these values manually here:
```js
if (currentMeta.length < collectionAttributes.length) {
      const attributes = currentMeta.map((e) => e.trait_type);
      const absent = collectionAttributes.filter((e) => !attributes.includes(e));

      absent.forEach((type) => {
        const rarityScoreNull = 1 / ((totalMetadata - tally[type].occurences) / totalMetadata);

        currentMeta.push({
          trait_type: type,
          value: null,
          rarityScore: roundToHundredth(rarityScoreNull)
        });

        totalRarity += rarityScoreNull;
      });
    }
```

**Comment by 0xSooki** [comment]
So the data fetched from Alchemy does not get assigned?

**Comment by 0xSooki** [comment]
Should work something like that, but something seems to be assigning null to every trait value, will investigate it further tonight

**Comment by fekete965** [comment]
I'll take a look at the saved records and compare it with the metadata as well today.

**Comment by 0xSooki** [comment]
Would appreciate that

**Comment by fekete965** [comment]
@0xSooki I did a little experiment.
I have saved all gathered NFT's metadata into its own file. Since we also have the IDs of each element, that made it very easy to find the correct json file related to the NFT.

In the pictures below you will see `NFT-335`. On the left-hand side, you can see all the attributes that this particular NFT has, which is only a `single` attribute. On the right-hand side, you can see that we populate the rest of the NFT's attributes with a `null` value.

As I mentioned it above, I believe this is the algorithm's expected behaviour, but please let me know if this should be something different, we might need to take a look at how we process the data. :)

<img width="1440" alt="Screenshot 2022-10-05 at 22 30 41" src="https://user-images.githubusercontent.com/24807482/194168472-484b29d6-7ca2-4bea-aefd-a85f2612ed90.png">
![Uploading Screenshot 2022-10-05 at 22.30.47.png…]()

**Comment by fekete965** [comment]
Why shouldn't the value be null if that NFT doesn't have an attribute like that? 🤔

**Comment by 0xSooki** [comment]
Then it should be, sorry I miss understood, but for some reason for me there were only nulls for values

**Comment by fekete965** [comment]
Can an NFT exist without any attributes? (I have a minimal knowledge regarding NFTs, sorry)

**Comment by 0xSooki** [comment]
For ERC-721 token standard not really because the token standard is:
```
{
  "description": "Friendly OpenSea Creature that enjoys long swims in the ocean.",
  "external_url": "https://openseacreatures.io/3",
  "image": "https://storage.googleapis.com/opensea-prod.appspot.com/puffs/3.png",
  "name": "Dave Starbelly",
  "attributes": [
    {
      "trait_type": "Base",
      "value": "Starfish"
    },
    ...
  ]
}
```
There can be cases when the `value` is `null`, when the given token does not have that specific trait but other than that in most cases it should have a value

**Comment by fekete965** [comment]
Alright. Thanks for explaining it to me!! 🙏 ❤️

**Comment by 0xSooki** [comment]
After the `null` issue is fixed we can merge `develop` into `main`

**Comment by fekete965** [comment]
I will keep investigating the issue when I have time.

**Comment by 0xSooki** [comment]
Much appreciated

**Comment by fekete965** [comment]
@0xSooki would you be able to send me your data set?
I cannot reproduce this issue anymore.

**Comment by 0xSooki** [comment]
Not the attribute list itself but the `values`
![image](https://user-images.githubusercontent.com/65089621/194476318-29d7b40d-9bd1-4dfb-8c3a-ca3df52f0b30.png)

**Comment by fekete965** [comment]
@0xSooki then I failed to understand the problem 😞 
Everything looks correct to me.

If you don't want attributes with null values, we simply remove the push from the code below:
```js
if (currentMeta.length < collectionAttributes.length) {
      const attributes = currentMeta.map((e) => e.trait_type);
      const absent = collectionAttributes.filter((e) => !attributes.includes(e));

      absent.forEach((type) => {
        const rarityScoreNull = 1 / ((totalMetadata - tally[type].occurences) / totalMetadata);

        currentMeta.push({
          trait_type: type,
          value: null,
          rarityScore: roundToHundredth(rarityScoreNull)
        });

        totalRarity += rarityScoreNull;
      });
    }
 ```
 
We gather every attribute from our dataset:
```js
ALL ATTRIBUTES
Set(11) {
  'Class',
  'Background',
  'Skin',
  'Antenna',
  'Mouth',
  'Eyes',
  'Clothes',
  'Mask',
  'Pet',
  'Special Set',
  'Stamina'
}
```

Afterwards, we compare the NFT's attribute list with the list above.
```js
// NFT's attribute list
Set(10) {
  'Class',
  'Background',
  'Skin',
  'Antenna',
  'Mouth',
  'Eyes',
  'Clothes',
  'Mask',
  'Pet',
  'Stamina'
}
```
In this list above, we are missing `Special Set`, so in our loop, we add this element to the NFT's attribute list and assign a `null` to it.

We can simply remove the push if you want to avoid having attributes with the value of `null`.

**Comment by 0xSooki** [comment]
Yupp, this works perfectly & just realised my problem might be with alchemy itself as now it doesen't even work on the backup, will try to write a detailed issue soon about what's in my mind
