### ISSUE TITLE
Loading indicator while the application is processing

### ISSUE THREAD

**Issue by fekete965** [0xSooki/nft-rarity-generator#14]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] This is a feature request only 💡
- [x] I checked to make sure that this feature has NOT already been requested

**Is your feature request related to a problem? Please describe.**
Without logging, we do not have any indication regarding the application's state.

**Why are you requesting this feature**
It would be nice to see a loader instead of all the currently processed data in the console.
We can also show the loader only in cases where we don't want logging.
The variable for logging could also come from the `.env` for easier handling.
I would also have some idea how we can make the CLI more user friendly.

**Describe the solution you'd like**
I can add a loading indicator while the application is processing NFT data.

**Comment by fekete965** [comment]
I am very happy to implement these changes to the code if needed. :)

**Comment by 0xSooki** [comment]
Feel free to do so, I love your enthusiasm towards the project :)
