### ISSUE TITLE
Run addtional validation on NFTs before DB insertion

### ISSUE THREAD

**Issue by fekete965** [0xSooki/nft-rarity-generator#16]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] This is a feature request only 💡
- [x] I checked to make sure that this feature has NOT already been requested

**Why are you requesting this feature**
I think it would be worth running validation on each item before we send data to the DB.

**Describe the solution you'd like**
Validate the created model before populating the insertable data list.
If it passes the validation we add it to the list otherwise, we save the error in a separate list.
We will prompt the user about the occurred errors and present it to the user on demand.

**Comment by fekete965** [comment]
I am also happy to work on this feature. :)

**Comment by 0xSooki** [comment]
Great idea, feel free to work on it :)
