### ISSUE TITLE
Refactor codebase

### ISSUE THREAD

**Issue by 0xSooki** [0xSooki/nft-rarity-generator#3]
## Expected Behavior

Break down the src folders content into multiple files/folders to improve readability

## Current Behavior

The current repo is not too understandable as everything is stored in 2-3 files

## Detailed Description

Break the codebase down into smaller more understandable chunks & functions. Adding comments to document the functions are welcome as well

**Comment by fekete965** [comment]
I am happy to pick this one up. :)

**Comment by 0xSooki** [comment]
Go ahead :)
