### ISSUE TITLE
Save data to database

### ISSUE THREAD

**Issue by 0xSooki** [0xSooki/nft-rarity-generator#4]
## Expected Behavior

Have the option to save the data in a database, preferably [MongoDB](https://www.mongodb.com/) but open to any other options

## Current Behavior

Currently it only saves the data locally in a JSON file in the build folder
 
## Detailed Description

Create the option to be able the save the generated data in a database. The file should be added to the database for later to be queried or used in applications

## Possible Implementation

- Check if the database exists locally or in the cloud
	- If it does connect to it & upload the generated data
	- Else create the database locally or in the cloud
		- Than upload the generated data

**Comment by cimok2000** [comment]
Hi! I'd love to work on this. I am use to using MongoDB and this would be possible to complete.

**Comment by 0xSooki** [comment]
Haii, that would be amazing

**Comment by cimok2000** [comment]
Hi sorry to comment, I'm not sure how the Hackathon works but do you have to add a tag for it to complete? Thanks! Let me know if theres anymore issues I could complete.
